//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRMS.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ammunition
    {
        public int Id { get; set; }
        public string Caliber { get; set; }
        public string Supplier { get; set; }
        public Nullable<int> Qty { get; set; }
    }
}
