//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRMS.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firearm
    {
        public int Id { get; set; }
        public string SerialNumber { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public int Location { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
