//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRMS.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int id { get; set; }
        public int EmployeeId { get; set; }
        public string ClassName { get; set; }
        public System.DateTime DateAttended { get; set; }
        public Nullable<int> TrainingHours { get; set; }
        public decimal Cost { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
