//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRMS.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int VehicleID { get; set; }
        public Nullable<int> VehicleNumber { get; set; }
        public int VIN { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string ModelYear { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<System.DateTime> DateOutOfService { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public bool IsInMaint { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
